# This compose file will replace watcharrs
# built in UI with a custom one provided in
# a named volume (for use with ui-build image).

services:
  watcharr:
    # We dont need to build here too for testing if
    # a custom ui works, so using latest prod image.
    image: ghcr.io/sbondco/watcharr:latest
    container_name: watcharr
    ports:
      - 3080:3080
    volumes:
      - ./container_data:/data
      - type: volume
        source: watcharr-ui
        target: /ui
        volume:
          nocopy: true
          subpath: build

volumes:
  watcharr-ui:
    external: true
