# Backend
FROM golang:1.20 AS server

WORKDIR /server
COPY server/*.go server/go.* ./

RUN go mod download && GOOS=linux go build -o ./watcharr

# Production
FROM debian:11.6 AS runner

COPY --from=server /server/watcharr /

EXPOSE 3080

CMD ["/watcharr"]
