# Multi arch support doc/guide:
# https://docs.docker.com/build/ci/github-actions/multi-platform/

name: Development Watcharr Image Release

on:
  workflow_dispatch:

env:
  image: ghcr.io/sbondco/watcharr

jobs:
  release-dev-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          # tags: ${{ env.image }}:dev
          labels: ${{ env.image }}:${{ github.sha }}
