name: Development Watcharr Container Release

on:
  workflow_dispatch:

jobs:
  release-images:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: true
      # Run for each dockerfile (one for server and one for ui images)
      matrix:
        include:
          - dockerfile: ./Dockerfile.svr
            image: ghcr.io/sbondco/watcharr
          - dockerfile: ./Dockerfile.ui
            image: ghcr.io/sbondco/watcharr-ui

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.image }}:dev
          labels: ${{ matrix.image }}:${{ github.sha }}
