name: Test PR Changes

on:
  pull_request:
    branches:
      - "**"
    tags-ignore:
      - v*

jobs:
  linter_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Get dependencies
        run: npm i

      - name: Check for linting/formatting errors
        run: npm run lint

  format_check_go:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5

      - name: gofmt test
        run: |
          outp=$(gofmt -l .)
          if [ -n "$outp" ]; then
            echo "Need to fix formatting!"
            echo "$outp"
            exit 1
          else
            echo "Everything looks formatted"
            exit 0
          fi
